flowchart LR
    %% Acteurs
    Visiteur((Visiteur))
    User((Utilisateur / Commercial))
    Admin((Administrateur))

    %% Généralisation (Héritage)
    Admin -. "Hérite de" .-> User
    User -. "Hérite de" .-> Visiteur

    %% Système
    subgraph CRM [Mini CRM M-Atici]
        UC0(S'inscrire)
        UC1(Se connecter de manière sécurisée)
        UC2(Gérer son carnet de clients)
        UC3(Créer et envoyer un devis)
        UC4(Générer un export PDF)
        UC5(Gérer tous les comptes utilisateurs)
        UC6(Consulter le CA de l'entreprise)
    end

    %% Relations
    Visiteur --> UC0
    User --> UC1
    User --> UC2
    User --> UC3
    User --> UC4
    Admin --> UC5
    Admin --> UC6
