name: CI simple

on: [push]

jobs:
  verifier-code:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Installer Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Test backend
        run: |
          cd backend
          npm install
          npx prisma generate
          npm test

      - name: Test frontend
        run: |
          cd frontend
          npm install
          npm run build

  deploiement:
    name: Déploiement Continu (CD)
    needs: verifier-code
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
      - name: Déploiement automatique sur le VPS OVH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd mon-projet-cda
            printf "EMAIL_USER=${{ secrets.EMAIL_USER }}\nEMAIL_PASS=${{ secrets.EMAIL_PASS }}\nEMAIL_FROM=${{ secrets.EMAIL_FROM }}\n" > .env
            git fetch origin && git reset --hard origin/main
            chmod +x deploy-staging.sh
            ./deploy-staging.sh
