name: CI simple

on: [push]

jobs:
  verifier-code:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Installer Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Test backend
        run: |
          cd backend
          npm install
          npx prisma generate
          npm test

      - name: Test frontend
        run: |
          cd frontend
          npm install
          npm run build

  deploiement:
    name: Déploiement Continu (CD)
    needs: verifier-code
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
      - name: Connexion au Serveur Cloud Privé (SSH)
        run: echo "Déploiement en cours via SSH/Rsync ou Docker Hub..."
        
      - name: Déploiement Frontend et Backend
        run: echo "Mise à jour de l'image Docker et redémarrage des services en production."
